spring.application.name=backend
# Poner solo los datos necesarios (medida de seguridad)
spring.datasource.url=jdbc:postgresql://ep-wispy-sound-anykx8bq-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
# Usuario de base de datos
spring.datasource.username=neondb_owner
# Contrasena de base de datos
spring.datasource.password=npg_DW8EUvm6IzKR
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.data.rest.base-path=