spring.application.name=backend
# Poner los datos que realmente se necesitan -> Medida de seguridad
spring.datasource.url=jdbc:postgresql://localhost:3306/bbdd
# Poner usuario
spring.datasource.username=escribe_aqui_tu_usuario
# Poner contraseña
spring.datasource.password=escribe_aqui_tu_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.data.rest.base-path=